import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Layouts from './MenuProfile'
export default  function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };

}>) {
  return (

      <div className="h-full ">
            <Layouts >
         {children}
          </Layouts>
      </div>

  );
}