import Toaster from "@/lib/toaster";
import ReduxProvider from "@/store/redux-provider";
import { lexend, poppins, roboto } from "@/types/font";
import type { Metadata } from "next";
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Layouts from './MenuProfile'
export default  function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };

}>) {
  return (

          <Layouts>
         {children}
          </Layouts>

  );
}