// import Toaster from "@/lib/toaster";
// import ReduxProvider from "@/store/redux-provider";
// import { lexend, poppins, roboto } from "@/types/font";
// import type { Metadata } from "next";
// import ScrollToTop from "@/components/Global/ScrollToTop";
// import { AppProvider } from "@/context/AppContext";
// import IntlProvider from "./IntlProvider";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// import "./globals.css";

// export default function MainLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//           <ReduxProvider>
//             <AppProvider>
//              {children}
//             </AppProvider>
//             <ScrollToTop />
//             <Toaster />
//           </ReduxProvider>
//   );
// }
