import Toaster from "@/lib/toaster";
import ReduxProvider from "@/store/redux-provider";
import { lexend, poppins, roboto } from "@/types/font";
import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import Header from "@/components/ui/pages/Header";
import Footer from '../../components/ui/pages/Footer'
import { AppProvider } from '../../context/AppContext'
import ScrollToTop from "@/components/Global/ScrollToTop";
import ProtectedRoute from "@/middleware/Midlewareathu";
import ThemeProvider from "@/theem/ThemeProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },

}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };

}>) {
  const messages = await getMessages();
  return (
    <html lang={ locale }>
      <body
        className={`${lexend?.variable} ${roboto?.variable} ${poppins?.variable}`}
      >
        <NextIntlClientProvider messages={messages}>
        <ReduxProvider>
          {/* <ThemeProvider> */}
          <Header />
          <AppProvider>
            <ProtectedRoute>
          <div className=" ">{children}</div>
          </ProtectedRoute>
          </AppProvider>
           <ScrollToTop />
          <Footer/>
          {/* </ThemeProvider> */}
          <Toaster />
        </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
