import Toaster from '@/lib/toaster'
import ReduxProvider from '@/store/redux-provider'
import type { Metadata } from 'next'
import ScrollToTop from '@/components/Global/ScrollToTop'
import { AppProvider } from '@/context/AppContext'

import Header from '../../components/ui/pages/Header/Header'
import Footer from '../../components/ui/pages/Footer'
import ProtectedRoute from '../../middleware/Midlewareathu'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
import { getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import './globals.css'
export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
            <AppProvider>
              <Header />
              <ProtectedRoute>{children}</ProtectedRoute>
              <Footer />
            </AppProvider>
            <div className="fixed bottom-10 right-20">
              <ScrollToTop />
            </div>
            <Toaster />
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
